# Agnes' Jupyter Project

In [1]:
1+1

2

In [2]:
3-4

-1

In [7]:
1/2

0.5

Strings - Markdown

"string" - Markdown

# String - Markdown starting with a "#"

In [9]:
nigeria = [1,2,3,4,5,6,7,8,9,10]

In [10]:
print(nigeria)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [11]:
nigeria[0]

1

In [12]:
nigeria.append(25)

In [13]:
nigeria

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 25]

In [16]:
hi = [1,2,3,[4,5,6,[7,8,9],11,12],13,14]

In [17]:
hi

[1, 2, 3, [4, 5, 6, [7, 8, 9], 11, 12], 13, 14]

In [18]:
hi[0]

1

In [21]:
hi[3]

[4, 5, 6, [7, 8, 9], 11, 12]

In [23]:
hi[3][0]

4

In [24]:
hi[3][3]

[7, 8, 9]

In [25]:
hi[4]

13

In [26]:
hi[3][3][1]

8

In [27]:
d = {'girl':'faith','boy':'Joe'}

In [28]:
d['girl']

'faith'

In [29]:
print(d['girl'])

faith


True

In [31]:
False

False

In [32]:
True + True

2

In [33]:
False + False

0

In [34]:
True + False

1

# TUPLES

In [35]:
g = (1,2,3)

In [36]:
g.append(4) #This is a comment 

AttributeError: 'tuple' object has no attribute 'append'

In [37]:
g[1]=5

TypeError: 'tuple' object does not support item assignment

# SETS - 1 '#'

## SETS - 2 '#'

### SETS - 3 '#'

In [38]:
de = {1,2, 3, 1, 3,4,5,5}

In [39]:
de

{1, 2, 3, 4, 5}

# COMPARISON

In [40]:
1==1

True

In [41]:
1==2

False

In [42]:
1>2

False

In [43]:
1<=2

True

In [44]:
'hi' =='HI'

False

In [46]:
'fine' =='good'

False

# LOGIC OPERATOR

In [48]:
(1>2) and (2<3)

False

(1==2) or (2<3)

In [53]:
i = 1
while i < 5:
    print('The current value of x is ',x)
    i=i+1

The current value of x is  10
The current value of x is  10
The current value of x is  10
The current value of x is  10


# if, elif, else statement

In [50]:
if 1==2:
    print('first')
elif 3<4:
    print('second')
else:
    print('last')

second


# FOR LOOP

In [51]:
items = [2,4,6,8,10]
for x in items:
    print(x)

2
4
6
8
10


# METHODS

In [54]:
name = 'hi, my name is Jon'

In [55]:
name.lower()

'hi, my name is jon'

In [56]:
name.upper()

'HI, MY NAME IS JON'

In [59]:
name = 'emma'
age = 10
print('My name is: {one}, and my age is: {two}'.format(one=name, two=age))

My name is: emma, and my age is: 10


i=1
while i<10:
    print('i is: {}'.format(i))
    i = i+1

# NUMPY

## This is Numerical Python. It is the basic python library on which some other libraries are built, such as Pandas

### Vectors(One Dimensional Array), Arrays, Matrices(List of lists, nested lists with equal number of itmes), Number Generation

In [64]:
import numpy as np

In [65]:
mylist = [1,2,3]

In [66]:
mylist

[1, 2, 3]

In [70]:
np.array([mylist])

array([[1, 2, 3]])

In [71]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [72]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Use of "arange" keyword. Arange the method in numpy used to generate arrays

In [73]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.arange(0,10,2)

array([0., 2., 4., 6., 8.])

In [85]:
np.arange(0,10,2,dtype = float)

array([0., 2., 4., 6., 8.])

In [82]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [83]:
np.zeros(10,dtype =int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [86]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [87]:
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [88]:
np.ones(3)

array([1., 1., 1.])

In [89]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [90]:
np.ones((3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## linspace

### Return evenly spaced numbers over a specific inerval

In [91]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [92]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [94]:
np.linspace(0,10,3)

array([  0.,  25.,  50.,  75., 100.])

In [96]:
np.eye(4) #An Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [108]:
np.random.random((2,2))

array([[0.7961326 , 0.13759844],
       [0.37286684, 0.29012296]])

In [112]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [126]:
a = np.random.random((2,3))

In [127]:
a

array([[0.73015808, 0.05344031, 0.85066779],
       [0.62968329, 0.07378291, 0.91987565]])

In [128]:
b = np.random.random((2,3))

In [129]:
c = np.add(a,b)

In [130]:
c

array([[1.29374181, 0.1970856 , 1.3046444 ],
       [1.30970186, 0.7824743 , 1.44723137]])

## randint

### Returns random integers from low to high (boundary inclusive)

In [131]:
np.random.randint(1,100)

83

In [134]:
np.random.randint(1000000,9999999,10)

array([9717868, 4722448, 2650626, 9189811, 1670119, 5642617, 5638973,
       7010596, 1844728, 7113022])

## Array Attributes and Methods

In [161]:
arr = np.arange(24)
ranarr = np.random.randint(0,50,10)

In [162]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [163]:
ranarr

array([39, 34, 48, 39, 44, 24, 10, 42, 41, 24])

## Reshape

### Returns an array containing the same data with a new shape

In [164]:
arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [165]:
arr.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [166]:
arr.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [167]:
arr.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

## max, min, argmax(ie position of the maximum value), argmin(ie position of the minimum value)

In [168]:
ranarr

array([39, 34, 48, 39, 44, 24, 10, 42, 41, 24])

In [169]:
ranarr.max()

48

In [170]:
ranarr.min()

10

In [171]:
ranarr.argmax()

2

In [172]:
ranarr.argmin()

6

In [173]:
arr.dtype

dtype('int32')

In [174]:
ranarr.dtype

dtype('int32')

In [175]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [176]:
arr[8]

8

In [177]:
arr[5:20] #In slicing, either arrays or lists, the first boundary is inclusive while the second boundary is not inclusive

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [178]:
arr[5]=0

In [190]:
arr

array([   0,    1,    2,    3,    4,    0,    6,    7,    8,    9, -100,
       -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
       -100, -100])

In [188]:
arr[10:20]

In [189]:
arr

array([   0,    1,    2,    3,    4,    0,    6,    7,    8,    9, -100,
       -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
       -100, -100])

# PANDAS

In [191]:
import pandas as pd

## Dataframe: This is a two dimensional labelled data structure with columns of potentially different types

In [213]:
s = pd.Series([3,-5,7,4],index=["a","b","c","d"])

In [198]:
s

a    3
b   -5
c    7
d    4
dtype: int64

In [201]:
s = pd.Series([3,-5,7,4]) #This gives a default index of serial numbers from 0

In [202]:
s

0    3
1   -5
2    7
3    4
dtype: int64

## Using a dictionary to create a dataframe

In [203]:
data = {"Country":["Belgium","Nigeria"], "Capital":["Brussels","Abuja"]}

In [211]:
pd.DataFrame(data,columns=["Country","Capital"])

Country   Capital
0  Belgium  Brussels
1  Nigeria     Abuja

### Creating Series with labels, lists, arrays, dictionaries

In [226]:
labels = ["a", "b", "c"]
my_list = [10, 20, 30]
arr = np.array([5, 15, 25])
d = {"a":11, "b":22,"c":33}

In [227]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [228]:
pd.Series(data=my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [229]:
pd.Series(arr, labels) #The first value in parenthesis os the data while the second is the index

a     5
b    15
c    25
dtype: int32

In [230]:
pd.Series(d) #Since a dicionary has kes and values, it automatically collects the keys and values it contains. Hence, we need one variable in the parenthesis

a    11
b    22
c    33
dtype: int64

In [236]:
ser1 = pd.Series([1,2,3,4], index = ["USA", "Germany", "USSR", "Japan"])

In [237]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [238]:
ser2 = pd.Series([1,2,3,4], index = ["USA", "Germany", "Italy", "Japan"])

In [239]:
ser2

USA        1
Germany    2
Italy      3
Japan      4
dtype: int64

In [244]:
ser1 + ser2 #The Nan because there is no corresponding thesame key to add in both indexes 

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [245]:
data = {"Country":["Belgium","Nigeria"], "Capital":["Brussels","Abuja"]}

In [246]:
data

{'Country': ['Belgium', 'Nigeria'], 'Capital': ['Brussels', 'Abuja']}

In [248]:
 df = pd.DataFrame(data,columns=["Country","Capital"])

In [249]:
df

Country   Capital
0  Belgium  Brussels
1  Nigeria     Abuja

In [250]:
df["Capital"]

0    Brussels
1       Abuja
Name: Capital, dtype: object

In [251]:
df["Country"]

0    Belgium
1    Nigeria
Name: Country, dtype: object

In [253]:
df["City"] = ["Kansas","Buari"]

In [254]:
df

Country   Capital    City
0  Belgium  Brussels  Kansas
1  Nigeria     Abuja   Buari

In [257]:
data = {"A":[45, 20, 15], "B":[56, 34, 12]}

In [258]:
data

{'A': [45, 20, 15], 'B': [56, 34, 12]}

In [259]:
 df = pd.DataFrame(data,columns=["A","B"])

In [260]:
df

A   B
0  45  56
1  20  34
2  15  12

In [261]:
df["C"] = df["A"]+df["B"]

In [262]:
df

A   B    C
0  45  56  101
1  20  34   54
2  15  12   27

In [263]:
df1 = df.drop("A", axis=1)

In [264]:
df1

B    C
0  56  101
1  34   54
2  12   27

In [265]:
df

A   B    C
0  45  56  101
1  20  34   54
2  15  12   27

In [266]:
df.drop("A", axis=1, inplace=True)

In [267]:
df

B    C
0  56  101
1  34   54
2  12   27

In [268]:
df.loc[1]

B    34
C    54
Name: 1, dtype: int64

In [270]:
df.loc[0]

B     56
C    101
Name: 0, dtype: int64

In [274]:
df.loc[2]

B    12
C    27
Name: 2, dtype: int64

In [275]:
df.loc[1, "C"]

54

In [276]:
df>50

B      C
0   True   True
1  False   True
2  False  False

In [277]:
df.max()

B     56
C    101
dtype: int64

In [280]:
df[df>50] #This prints out only the numbers greater than 50

B      C
0  56.0  101.0
1   NaN   54.0
2   NaN    NaN

# Loading an external file such as csv, excel, text, etc 

### To read csv file: pd.read_excel("file.xlsx")
### To rae
### To
### To

In [281]:
sal = pd.read_csv("Salaries.csv")

In [282]:
sal

Id            EmployeeName  \
0            1          NATHANIEL FORD   
1            2            GARY JIMENEZ   
2            3          ALBERT PARDINI   
3            4       CHRISTOPHER CHONG   
4            5         PATRICK GARDNER   
5            6          DAVID SULLIVAN   
6            7               ALSON LEE   
7            8           DAVID KUSHNER   
8            9          MICHAEL MORRIS   
9           10      JOANNE HAYES-WHITE   
10          11           ARTHUR KENNEY   
11          12        PATRICIA JACKSON   
12          13       EDWARD HARRINGTON   
13          14             JOHN MARTIN   
14          15          DAVID FRANKLIN   
15          16         RICHARD CORRIEA   
16          17                AMY HART   
17          18          SEBASTIAN WONG   
18          19              MARTY ROSS   
19          20           ELLEN MOFFATT   
20          21              VENUS AZAR   
21          22            JUDY MELINEK   
22          23           GEORGE GARCIA   
23          24           VICTOR WYRSCH   
24          25         JOSEPH DRISCOLL   
25          26            GREGORY SUHR   
26          27             JOHN HANLEY   
27          28          RAYMOND GUZMAN   
28          29          DENISE SCHMITT   
29          30           MONICA FIELDS   
...        ...                     ...   
148624  148625      Lorraine Rosenthal   
148625  148626         Renato C Gurion   
148626  148627           Paulet Gaines   
148627  148628        Brett A Lundberg   
148628  148629          Mark W Mcclure   
148629  148630       Elizabeth Iniguez   
148630  148631            Randy J Keys   
148631  148632         Andre M Johnson   
148632  148633  Sharon D Owens-Webster   
148633  148634        Edward Ferdinand   
148634  148635          David M Turner   
148635  148636     James S Kibblewhite   
148636  148637           Andrew J Enzi   
148637  148638        Kadeshra D Green   
148638  148639    Lennard B Hutchinson   
148639  148640       Richard A Talbert   
148640  148641      Charlene D Mccully   
148641  148642   Raphael Marquis Goins   
148642  148643       Dominic C Marquez   
148643  148644              Kim Brewer   
148644  148645            Randy D Winn   
148645  148646        Carolyn A Wilson   
148646  148647            Not provided   
148647  148648          Joann Anderson   
148648  148649             Leon Walker   
148649  148650           Roy I Tillery   
148650  148651            Not provided   
148651  148652            Not provided   
148652  148653            Not provided   
148653  148654               Joe Lopez   

                                                JobTitle    BasePay  \
0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                        CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                        CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
5                              ASSISTANT DEPUTY CHIEF II  118602.00   
6                     BATTALION CHIEF, (FIRE DEPARTMENT)   92492.01   
7                         DEPUTY DIRECTOR OF INVESTMENTS  256576.96   
8                     BATTALION CHIEF, (FIRE DEPARTMENT)  176932.64   
9                 CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)  285262.00   
10      ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)  194999.39   
11                       CAPTAIN III (POLICE DEPARTMENT)   99722.00   
12                           EXECUTIVE CONTRACT EMPLOYEE  294580.02   
13                                     DEPARTMENT HEAD V  271329.03   
14                    BATTALION CHIEF, (FIRE DEPARTMENT)  174872.64   
15                    COMMANDER III, (POLICE DEPARTMENT)  198778.01   
16                                     DEPARTMENT HEAD V  268604.57   
17                 CAPTAIN, EMERGENCYCY MEDICAL SERVICES  140546.87   
18                    BATTALION CHIEF, (FIRE DEPARTMENT)  

In [283]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [284]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
Id                  148654 non-null int64
EmployeeName        148654 non-null object
JobTitle            148654 non-null object
BasePay             148045 non-null float64
OvertimePay         148650 non-null float64
OtherPay            148650 non-null float64
Benefits            112491 non-null float64
TotalPay            148654 non-null float64
TotalPayBenefits    148654 non-null float64
Year                148654 non-null int64
Notes               0 non-null float64
Agency              148654 non-null object
Status              0 non-null float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [285]:
sal["BasePay"].mean()

66325.44884050643

In [286]:
sal["OvertimePay"].max()

245131.88

#### What is the job title of Joseph Driscoll

In [287]:
sal[sal["EmployeeName"]=="JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

#### What is the Total Pay Benefit of Joseph Driscoll

In [288]:
sal[sal["EmployeeName"]=="JOSEPH DRISCOLL"]["TotalPayBenefits"]

24    270324.91
Name: TotalPayBenefits, dtype: float64